namespace GoblinTweaks.UI;

/// <summary>
/// Self-contained localization for the Crafting Materials window. Its language is chosen in the
/// tweak settings (independently of the GoblinTweaks UI language). English and Spanish are complete;
/// German/French/Japanese cover the short labels and fall back to English for the longer help text.
/// </summary>
internal static class CraftLoc
{
    /// <summary>Active language code ("en"/"es"/"de"/"fr"/"ja"), set by the addon.</summary>
    public static string Lang = "en";

    public static string Get(string key)
    {
        if (Tables.TryGetValue(Lang, out var table) && table.TryGetValue(key, out var value))
            return value;
        return Tables["en"].TryGetValue(key, out var en) ? en : key;
    }

    public static string Fmt(string key, params object[] args) => string.Format(Get(key), args);

    private static readonly Dictionary<string, Dictionary<string, string>> Tables = new()
    {
        ["en"] = new()
        {
            ["title"] = "Crafting Materials",
            ["status.ready"] = "Can Craft",
            ["status.almost"] = "Almost",
            ["status.cant"] = "Can't Craft",
            ["hdr.status"] = "STATUS",
            ["hdr.category"] = "CATEGORY",
            ["search"] = "Search recipes…",
            ["tip.refresh"] = "Refresh inventory scan",
            ["filter.hidecrafted"] = "Hide crafted",
            ["filter.sort"] = "Sort",
            ["filter.class"] = "Class",
            ["sort.name"] = "Name",
            ["sort.status"] = "Craft status",
            ["sort.level"] = "Item level",
            ["sort.missing"] = "Fewest missing",
            ["class.all"] = "All classes",
            ["tip.sortdir"] = "Reverse sort direction",
            ["tip.help"] = "Help, legend and tips",
            ["bottom.showing"] = "Showing {0}",
            ["bottom.crafted"] = "Crafted {0} / {1}",
            ["detail.placeholder"] = "← Select a recipe to see its ingredients.",
            ["detail.crafted"] = "Already crafted",
            ["detail.ingredients"] = "Ingredients:",
            ["market.loading"] = "Market  loading…",
            ["market.price"] = "Market  avg {0}g  ·  min {1}g",
            ["market.none"] = "Market  no recent listings",
            ["loc.notfound"] = "Not found",
            ["loc.mainbags"] = "Main bags",
            ["loc.otherinv"] = "Other inv.",
            ["loc.yourbags"] = "Your Bags",
            ["loc.bagsof"] = "{0} - Bags",
            ["loc.saddlebag"] = "Saddlebag",
            ["loc.retainers"] = "Retainer(s)",
            ["loc.fcchest"] = "FC Chest",
            ["help.title"] = "Crafting Materials — Help",
            ["help.cat"] = "CATEGORY",
            ["help.nav.guide"] = "Guide",
            ["help.nav.colors"] = "Color legend",
            ["help.nav.icons"] = "Icons & filters",
            ["help.nav.tips"] = "Tips",
            ["help.guide.p1"] = "Crafting Materials cross-references every craftable recipe against your bags, saddlebag, retainers and FC chest, and shows what you can make right now.",
            ["help.guide.p2"] = "Browse with the lists on the left, filter with the search box, and refine with the sort and class controls in the top bar.",
            ["help.colors.green.kw"] = "Green",
            ["help.colors.green.tx"] = "every material is in your main bags — craft it right now.",
            ["help.colors.yellow.kw"] = "Yellow",
            ["help.colors.yellow.tx"] = "you own everything, but some sits in the saddlebag, a retainer or the FC chest.",
            ["help.colors.orange.kw"] = "Orange",
            ["help.colors.orange.tx"] = "almost there — only one or two material types are missing.",
            ["help.colors.grey.kw"] = "Grey",
            ["help.colors.grey.tx"] = "too many materials are missing to craft it.",
            ["help.colors.chips.kw"] = "Chips",
            ["help.colors.chips.tx"] = "ingredient chips are green when you have enough, yellow when it's in another inventory, red when missing.",
            ["help.icons.check.kw"] = "Check",
            ["help.icons.check.tx"] = "a green check means you have crafted this recipe at least once.",
            ["help.icons.hide.kw"] = "Hide crafted",
            ["help.icons.hide.tx"] = "removes recipes you have already made.",
            ["help.icons.sort.kw"] = "Sort",
            ["help.icons.sort.tx"] = "order by Name, Craft status, Item level or Fewest missing — the arrow flips direction.",
            ["help.icons.class.kw"] = "Class",
            ["help.icons.class.tx"] = "show only one crafter's recipes.",
            ["help.icons.refresh.kw"] = "Refresh",
            ["help.icons.refresh.tx"] = "the button by the search box rescans every inventory.",
            ["help.tips.t1"] = "Right-click a material to open the game's item menu (Search for Item, Link, Search Recipes…).",
            ["help.tips.t2"] = "Right-click a recipe to open it directly in the Crafting Log.",
            ["help.tips.t3"] = "Hover any item to see the full in-game tooltip.",
            ["help.tips.t4"] = "The bottom bar shows how many recipes are listed and your overall crafted progress.",
        },

        ["es"] = new()
        {
            ["title"] = "Materiales de Crafteo",
            ["status.ready"] = "Puedo craftear",
            ["status.almost"] = "Casi",
            ["status.cant"] = "No puedo",
            ["hdr.status"] = "ESTADO",
            ["hdr.category"] = "CATEGORÍA",
            ["search"] = "Buscar recetas…",
            ["tip.refresh"] = "Reescanear inventarios",
            ["filter.hidecrafted"] = "Ocultar crafteadas",
            ["filter.sort"] = "Orden",
            ["filter.class"] = "Clase",
            ["sort.name"] = "Nombre",
            ["sort.status"] = "Estado",
            ["sort.level"] = "Nivel de ítem",
            ["sort.missing"] = "Menos faltantes",
            ["class.all"] = "Todas las clases",
            ["tip.sortdir"] = "Invertir el orden",
            ["tip.help"] = "Ayuda y leyenda",
            ["bottom.showing"] = "Mostrando {0}",
            ["bottom.crafted"] = "Crafteadas {0} / {1}",
            ["detail.placeholder"] = "← Seleccioná una receta para ver sus ingredientes.",
            ["detail.crafted"] = "Ya crafteada",
            ["detail.ingredients"] = "Ingredientes:",
            ["market.loading"] = "Mercado  cargando…",
            ["market.price"] = "Mercado  prom {0}g  ·  mín {1}g",
            ["market.none"] = "Mercado  sin publicaciones",
            ["loc.notfound"] = "No está",
            ["loc.mainbags"] = "Bolsas principales",
            ["loc.otherinv"] = "Otro inv.",
            ["loc.yourbags"] = "Tus bolsas",
            ["loc.bagsof"] = "{0} - Bolsas",
            ["loc.saddlebag"] = "Saddlebag",
            ["loc.retainers"] = "Retainer(s)",
            ["loc.fcchest"] = "Baúl de FC",
            ["help.title"] = "Materiales de Crafteo — Ayuda",
            ["help.cat"] = "CATEGORÍA",
            ["help.nav.guide"] = "Guía",
            ["help.nav.colors"] = "Leyenda de colores",
            ["help.nav.icons"] = "Íconos y filtros",
            ["help.nav.tips"] = "Consejos",
            ["help.guide.p1"] = "Materiales de Crafteo cruza cada receta crafteable con tus bolsas, saddlebag, retainers y baúl de la FC, y te muestra qué podés fabricar ahora.",
            ["help.guide.p2"] = "Navegá con las listas de la izquierda, filtrá con el buscador y afiná con el orden y la clase en la barra superior.",
            ["help.colors.green.kw"] = "Verde",
            ["help.colors.green.tx"] = "todos los materiales están en tus bolsas — craftealo ya.",
            ["help.colors.yellow.kw"] = "Amarillo",
            ["help.colors.yellow.tx"] = "tenés todo, pero algo está en la saddlebag, un retainer o el baúl de FC.",
            ["help.colors.orange.kw"] = "Naranja",
            ["help.colors.orange.tx"] = "casi — solo faltan uno o dos tipos de material.",
            ["help.colors.grey.kw"] = "Gris",
            ["help.colors.grey.tx"] = "faltan demasiados materiales.",
            ["help.colors.chips.kw"] = "Fichas",
            ["help.colors.chips.tx"] = "las fichas de ingredientes son verdes si tenés suficiente, amarillas si está en otro inventario, rojas si falta.",
            ["help.icons.check.kw"] = "Check",
            ["help.icons.check.tx"] = "un check verde significa que ya crafteaste esta receta al menos una vez.",
            ["help.icons.hide.kw"] = "Ocultar crafteadas",
            ["help.icons.hide.tx"] = "quita las recetas que ya hiciste.",
            ["help.icons.sort.kw"] = "Orden",
            ["help.icons.sort.tx"] = "ordená por Nombre, Estado, Nivel o Menos faltantes — la flecha invierte el sentido.",
            ["help.icons.class.kw"] = "Clase",
            ["help.icons.class.tx"] = "muestra solo las recetas de un crafter.",
            ["help.icons.refresh.kw"] = "Actualizar",
            ["help.icons.refresh.tx"] = "el botón junto al buscador reescanea todos los inventarios.",
            ["help.tips.t1"] = "Click derecho en un material para abrir el menú del juego (Search for Item, Link, Search Recipes…).",
            ["help.tips.t2"] = "Click derecho en una receta para abrirla en el Crafting Log.",
            ["help.tips.t3"] = "Pasá el mouse sobre un ítem para ver el tooltip completo del juego.",
            ["help.tips.t4"] = "La barra inferior muestra cuántas recetas se listan y tu progreso total de crafteo.",
        },

        ["de"] = new()
        {
            ["title"] = "Handwerksmaterialien",
            ["status.ready"] = "Herstellbar",
            ["status.almost"] = "Fast",
            ["status.cant"] = "Nicht möglich",
            ["hdr.status"] = "STATUS",
            ["hdr.category"] = "KATEGORIE",
            ["search"] = "Rezepte suchen…",
            ["tip.refresh"] = "Inventar neu einlesen",
            ["filter.hidecrafted"] = "Hergestellte ausblenden",
            ["filter.sort"] = "Sortieren",
            ["filter.class"] = "Klasse",
            ["sort.name"] = "Name",
            ["sort.status"] = "Status",
            ["sort.level"] = "Gegenstandsstufe",
            ["sort.missing"] = "Wenigste fehlen",
            ["class.all"] = "Alle Klassen",
            ["tip.sortdir"] = "Sortierrichtung umkehren",
            ["tip.help"] = "Hilfe und Legende",
            ["bottom.showing"] = "Zeige {0}",
            ["bottom.crafted"] = "Hergestellt {0} / {1}",
            ["detail.placeholder"] = "← Wähle ein Rezept, um die Zutaten zu sehen.",
            ["detail.crafted"] = "Bereits hergestellt",
            ["detail.ingredients"] = "Zutaten:",
            ["market.loading"] = "Markt  lädt…",
            ["market.price"] = "Markt  Ø {0}g  ·  min {1}g",
            ["market.none"] = "Markt  keine Angebote",
            ["loc.notfound"] = "Nicht gefunden",
            ["loc.mainbags"] = "Haupttasche",
            ["loc.otherinv"] = "Anderes Inv.",
            ["loc.yourbags"] = "Deine Taschen",
            ["loc.bagsof"] = "{0} - Taschen",
            ["loc.saddlebag"] = "Satteltasche",
            ["loc.retainers"] = "Gehilfe(n)",
            ["loc.fcchest"] = "FG-Truhe",
            ["help.title"] = "Handwerksmaterialien — Hilfe",
            ["help.cat"] = "KATEGORIE",
            ["help.nav.guide"] = "Anleitung",
            ["help.nav.colors"] = "Farblegende",
            ["help.nav.icons"] = "Symbole & Filter",
            ["help.nav.tips"] = "Tipps",
        },

        ["fr"] = new()
        {
            ["title"] = "Matériaux d'artisanat",
            ["status.ready"] = "Réalisable",
            ["status.almost"] = "Presque",
            ["status.cant"] = "Impossible",
            ["hdr.status"] = "STATUT",
            ["hdr.category"] = "CATÉGORIE",
            ["search"] = "Rechercher des recettes…",
            ["tip.refresh"] = "Rescanner l'inventaire",
            ["filter.hidecrafted"] = "Masquer les fabriquées",
            ["filter.sort"] = "Trier",
            ["filter.class"] = "Classe",
            ["sort.name"] = "Nom",
            ["sort.status"] = "Statut",
            ["sort.level"] = "Niveau d'objet",
            ["sort.missing"] = "Moins manquants",
            ["class.all"] = "Toutes les classes",
            ["tip.sortdir"] = "Inverser le sens du tri",
            ["tip.help"] = "Aide et légende",
            ["bottom.showing"] = "Affichés {0}",
            ["bottom.crafted"] = "Fabriqués {0} / {1}",
            ["detail.placeholder"] = "← Sélectionne une recette pour voir les ingrédients.",
            ["detail.crafted"] = "Déjà fabriquée",
            ["detail.ingredients"] = "Ingrédients :",
            ["market.loading"] = "Marché  chargement…",
            ["market.price"] = "Marché  moy {0}g  ·  min {1}g",
            ["market.none"] = "Marché  aucune offre",
            ["loc.notfound"] = "Introuvable",
            ["loc.mainbags"] = "Sacs principaux",
            ["loc.otherinv"] = "Autre inv.",
            ["loc.yourbags"] = "Tes sacs",
            ["loc.bagsof"] = "{0} - Sacs",
            ["loc.saddlebag"] = "Sacoche",
            ["loc.retainers"] = "Serviteur(s)",
            ["loc.fcchest"] = "Coffre de CL",
            ["help.title"] = "Matériaux d'artisanat — Aide",
            ["help.cat"] = "CATÉGORIE",
            ["help.nav.guide"] = "Guide",
            ["help.nav.colors"] = "Légende des couleurs",
            ["help.nav.icons"] = "Icônes et filtres",
            ["help.nav.tips"] = "Astuces",
        },

        ["ja"] = new()
        {
            ["title"] = "製作素材",
            ["status.ready"] = "製作可能",
            ["status.almost"] = "もう少し",
            ["status.cant"] = "製作不可",
            ["hdr.status"] = "ステータス",
            ["hdr.category"] = "カテゴリ",
            ["search"] = "レシピを検索…",
            ["tip.refresh"] = "所持品を再スキャン",
            ["filter.hidecrafted"] = "製作済みを隠す",
            ["filter.sort"] = "並び替え",
            ["filter.class"] = "クラス",
            ["sort.name"] = "名前",
            ["sort.status"] = "製作状況",
            ["sort.level"] = "アイテムレベル",
            ["sort.missing"] = "不足が少ない順",
            ["class.all"] = "全クラス",
            ["tip.sortdir"] = "並び順を反転",
            ["tip.help"] = "ヘルプと凡例",
            ["bottom.showing"] = "表示 {0}",
            ["bottom.crafted"] = "製作済み {0} / {1}",
            ["detail.placeholder"] = "← レシピを選ぶと材料が表示されます。",
            ["detail.crafted"] = "製作済み",
            ["detail.ingredients"] = "材料：",
            ["market.loading"] = "マーケット  読込中…",
            ["market.price"] = "マーケット  平均 {0}g  ·  最安 {1}g",
            ["market.none"] = "マーケット  出品なし",
            ["loc.notfound"] = "なし",
            ["loc.mainbags"] = "所持品",
            ["loc.otherinv"] = "他の所持先",
            ["loc.yourbags"] = "あなたの所持品",
            ["loc.bagsof"] = "{0} - 所持品",
            ["loc.saddlebag"] = "チョコボ鞄",
            ["loc.retainers"] = "リテイナー",
            ["loc.fcchest"] = "FCチェスト",
            ["help.title"] = "製作素材 — ヘルプ",
            ["help.cat"] = "カテゴリ",
            ["help.nav.guide"] = "ガイド",
            ["help.nav.colors"] = "色の凡例",
            ["help.nav.icons"] = "アイコンとフィルター",
            ["help.nav.tips"] = "ヒント",
        },
    };
}
