namespace GoblinTweaks.UI;

/// <summary>
/// Self-contained localization for the Crafting Materials window. Its language is chosen in the
/// tweak settings (independently of the GoblinTweaks UI language). English and Spanish are both complete.
/// </summary>
internal static class CraftLoc
{
    /// <summary>Active language code ("en"/"es"), set by the addon.</summary>
    public static string Lang = "en";

    public static string Get(string key)
    {
        if (Tables.TryGetValue(Lang, out var table) && table.TryGetValue(key, out var value))
            return value;
        return Tables["en"].TryGetValue(key, out var en) ? en : key;
    }

    public static string Fmt(string key, params object[] args) => string.Format(Get(key), args);

    private static readonly Dictionary<string, Dictionary<string, string>> Tables = new()
    {
        ["en"] = new()
        {
            ["title"] = "Crafting Materials",
            ["status.all"] = "All Recipes",
            ["status.ready"] = "Can Craft",
            ["status.almost"] = "Almost",
            ["status.cant"] = "Can't Craft",
            ["hdr.status"] = "STATUS",
            ["hdr.category"] = "CATEGORY",
            ["search"] = "Search recipes…",
            ["tip.refresh"] = "Refresh inventory scan",
            ["filter.hidecrafted"] = "Hide crafted",
            ["filter.hidenonlog"]  = "Hide non-log",
            ["filter.sort"] = "Sort",
            ["filter.class"] = "Class",
            ["sort.name"] = "Name",
            ["sort.status"] = "Craft status",
            ["sort.level"] = "Item level",
            ["sort.missing"] = "Fewest missing",
            ["sort.market"] = "Market price",
            ["class.all"] = "All classes",
            ["tip.sortdir"] = "Reverse sort direction",
            ["tip.help"] = "Help, legend and tips",
            ["tip.settings"] = "Settings",
            ["bottom.showing"] = "Showing {0}",
            ["bottom.crafted"] = "Crafted {0} / {1}",
            ["detail.placeholder"] = "← Select a recipe to see its ingredients.",
            ["detail.crafted"] = "Already crafted",
            ["detail.ingredients"] = "Ingredients:",
            ["market.loading"] = "Market  loading…",
            ["market.price"] = "Market  avg {0}g  ·  min {1}g",
            ["market.none"] = "Market  no recent listings",
            ["loc.notfound"] = "Not found",
            ["loc.mainbags"] = "Main bags",
            ["loc.otherinv"] = "Other inv.",
            ["loc.yourbags"] = "Your Bags",
            ["loc.bagsof"] = "{0} - Bags",
            ["loc.saddlebag"] = "Saddlebag",
            ["loc.retainers"] = "Retainer(s)",
            ["loc.fcchest"] = "FC Chest",
            ["help.title"] = "Crafting Materials — Help",
            ["help.cat"] = "CATEGORY",
            ["help.nav.guide"] = "Guide",
            ["help.nav.colors"] = "Color legend",
            ["help.nav.icons"] = "Icons & filters",
            ["help.nav.tips"] = "Tips",
            ["help.guide.p1"] = "Crafting Materials cross-references every craftable recipe against your bags, saddlebag, retainers and FC chest, and shows what you can make right now.",
            ["help.guide.p2"] = "Browse with the lists on the left, filter with the search box, and refine with the sort and class controls in the top bar.",
            ["help.colors.green.kw"] = "Green",
            ["help.colors.green.tx"] = "every material is in your main bags — craft it right now.",
            ["help.colors.yellow.kw"] = "Yellow",
            ["help.colors.yellow.tx"] = "you own everything, but some sits in the saddlebag, a retainer or the FC chest.",
            ["help.colors.orange.kw"] = "Orange",
            ["help.colors.orange.tx"] = "almost there — only one or two material types are missing.",
            ["help.colors.grey.kw"] = "Grey",
            ["help.colors.grey.tx"] = "too many materials are missing to craft it.",
            ["help.colors.chips.kw"] = "Chips",
            ["help.colors.chips.tx"] = "ingredient chips are green when you have enough, yellow when it's in another inventory, red when missing.",
            ["help.icons.check.kw"] = "✓  Check",
            ["help.icons.check.tx"] = "a green check marks recipes you have crafted at least once (basic and special housing only).",
            ["help.icons.dot.kw"]   = "●  Dot",
            ["help.icons.dot.tx"]   = "a grey dot marks recipes not counted by the crafting log — master recipe books or special non-housing items.",
            ["help.icons.hide.kw"]  = "Hide crafted",
            ["help.icons.hide.tx"]  = "removes recipes you have already made.",
            ["help.icons.hidenonlog.kw"] = "Hide non-log",
            ["help.icons.hidenonlog.tx"] = "removes master recipe and special non-housing recipes, keeping only basic and housing-category recipes that count toward the crafting log.",
            ["help.icons.sort.kw"]  = "Sort",
            ["help.icons.sort.tx"]  = "order by Name, Craft status, Item level, Fewest missing, or Market price — the arrow reverses direction. Market price uses Universalis data loaded in the background.",
            ["help.icons.class.kw"] = "Class",
            ["help.icons.class.tx"] = "show only one crafter's recipes.",
            ["help.icons.refresh.kw"] = "Refresh",
            ["help.icons.refresh.tx"] = "the button by the search box rescans every inventory.",
            ["help.icons.allrecipes.kw"] = "All Recipes",
            ["help.icons.allrecipes.tx"] = "the first entry in the STATUS sidebar shows every recipe regardless of craft status.",
            ["help.tips.t1"] = "Right-click a green ingredient to open the game's item menu. Yellow ingredients in the saddlebag also open the item menu. Red (missing) ingredients open their own recipe in the Crafting Log if they are craftable.",
            ["help.tips.t2"] = "Right-click a recipe row to open it in the Crafting Log.",
            ["help.tips.t3"] = "Hover any item to see the full in-game tooltip.",
            ["help.tips.t4"] = "The bottom bar shows how many recipes are listed and your overall crafted progress.",
            ["help.tips.t5"] = "When an ingredient is spread across multiple inventories, the hover tooltip breaks down each location with its HQ count — e.g. Retainer: 5 (2 HQ).",
        },

        ["es"] = new()
        {
            ["title"] = "Materiales de Crafteo",
            ["status.all"] = "Todas",
            ["status.ready"] = "Puedo craftear",
            ["status.almost"] = "Casi",
            ["status.cant"] = "No puedo",
            ["hdr.status"] = "ESTADO",
            ["hdr.category"] = "CATEGORÍA",
            ["search"] = "Buscar recetas…",
            ["tip.refresh"] = "Reescanear inventarios",
            ["filter.hidecrafted"] = "Ocultar crafteadas",
            ["filter.hidenonlog"]  = "Ocultar no-log",
            ["filter.sort"] = "Orden",
            ["filter.class"] = "Clase",
            ["sort.name"] = "Nombre",
            ["sort.status"] = "Estado",
            ["sort.level"] = "Nivel de ítem",
            ["sort.missing"] = "Menos faltantes",
            ["sort.market"] = "Precio de mercado",
            ["class.all"] = "Todas las clases",
            ["tip.sortdir"] = "Invertir el orden",
            ["tip.help"] = "Ayuda y leyenda",
            ["tip.settings"] = "Ajustes",
            ["bottom.showing"] = "Mostrando {0}",
            ["bottom.crafted"] = "Crafteadas {0} / {1}",
            ["detail.placeholder"] = "← Seleccioná una receta para ver sus ingredientes.",
            ["detail.crafted"] = "Ya crafteada",
            ["detail.ingredients"] = "Ingredientes:",
            ["market.loading"] = "Mercado  cargando…",
            ["market.price"] = "Mercado  prom {0}g  ·  mín {1}g",
            ["market.none"] = "Mercado  sin publicaciones",
            ["loc.notfound"] = "No está",
            ["loc.mainbags"] = "Bolsas principales",
            ["loc.otherinv"] = "Otro inv.",
            ["loc.yourbags"] = "Tus bolsas",
            ["loc.bagsof"] = "{0} - Bolsas",
            ["loc.saddlebag"] = "Saddlebag",
            ["loc.retainers"] = "Retainer(s)",
            ["loc.fcchest"] = "Baúl de FC",
            ["help.title"] = "Materiales de Crafteo — Ayuda",
            ["help.cat"] = "CATEGORÍA",
            ["help.nav.guide"] = "Guía",
            ["help.nav.colors"] = "Leyenda de colores",
            ["help.nav.icons"] = "Íconos y filtros",
            ["help.nav.tips"] = "Consejos",
            ["help.guide.p1"] = "Materiales de Crafteo cruza cada receta crafteable con tus bolsas, saddlebag, retainers y baúl de la FC, y te muestra qué podés fabricar ahora.",
            ["help.guide.p2"] = "Navegá con las listas de la izquierda, filtrá con el buscador y afiná con el orden y la clase en la barra superior.",
            ["help.colors.green.kw"] = "Verde",
            ["help.colors.green.tx"] = "todos los materiales están en tus bolsas — craftealo ya.",
            ["help.colors.yellow.kw"] = "Amarillo",
            ["help.colors.yellow.tx"] = "tenés todo, pero algo está en la saddlebag, un retainer o el baúl de FC.",
            ["help.colors.orange.kw"] = "Naranja",
            ["help.colors.orange.tx"] = "casi — solo faltan uno o dos tipos de material.",
            ["help.colors.grey.kw"] = "Gris",
            ["help.colors.grey.tx"] = "faltan demasiados materiales.",
            ["help.colors.chips.kw"] = "Fichas",
            ["help.colors.chips.tx"] = "las fichas de ingredientes son verdes si tenés suficiente, amarillas si está en otro inventario, rojas si falta.",
            ["help.icons.check.kw"] = "✓  Check",
            ["help.icons.check.tx"] = "un check verde indica que ya crafteaste esta receta (solo recetas básicas y especiales de housing).",
            ["help.icons.dot.kw"]   = "●  Punto",
            ["help.icons.dot.tx"]   = "un punto gris indica recetas que el crafting log no cuenta — libros de recetas maestras o especiales no-housing.",
            ["help.icons.hide.kw"]  = "Ocultar crafteadas",
            ["help.icons.hide.tx"]  = "quita del listado las recetas que ya hiciste.",
            ["help.icons.hidenonlog.kw"] = "Ocultar no-log",
            ["help.icons.hidenonlog.tx"] = "quita las recetas maestras y especiales no-housing, dejando solo las básicas y de housing que cuentan en el crafting log.",
            ["help.icons.sort.kw"]  = "Orden",
            ["help.icons.sort.tx"]  = "ordenar por Nombre, Estado, Nivel, Menos faltantes o Precio de mercado — la flecha invierte el sentido. El precio usa datos de Universalis que se cargan en segundo plano.",
            ["help.icons.class.kw"] = "Clase",
            ["help.icons.class.tx"] = "muestra solo las recetas de un crafter.",
            ["help.icons.refresh.kw"] = "Actualizar",
            ["help.icons.refresh.tx"] = "el botón junto al buscador reescanea todos los inventarios.",
            ["help.icons.allrecipes.kw"] = "Todas",
            ["help.icons.allrecipes.tx"] = "el primer item del panel STATUS muestra todas las recetas sin importar el estado.",
            ["help.tips.t1"] = "Click derecho en un ingrediente verde abre el menú del juego. Los amarillos en la saddlebag también abren el menú. Los rojos (faltantes) abren su propia receta en el Crafting Log si son crafteables.",
            ["help.tips.t2"] = "Click derecho en una receta la abre directamente en el Crafting Log.",
            ["help.tips.t3"] = "Pasá el mouse sobre un ítem para ver el tooltip completo del juego.",
            ["help.tips.t4"] = "La barra inferior muestra cuántas recetas se listan y tu progreso total de crafteo.",
            ["help.tips.t5"] = "Cuando un ingrediente está en varios inventarios, el tooltip desglosa cada lugar con su cantidad HQ — ej. Retainer: 5 (2 HQ).",
        },
    };
}
